# Propiedades comunes a todos los entornos
spring.application.name=indievivo-backend
server.port=8080

spring.datasource.url=jdbc:mariadb://bbdd.juangabrielsv.dev:3306/u665594306_bdapp
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.open-in-view=false

logging.level.root=INFO

# Perfil activo por defecto (para desarrollo local)
spring.profiles.active=dev