# Puerto del servidor local donde correrá la aplicación.
server.port=8080

# Configuración de la conexión a la base de datos.
spring.datasource.url=jdbc:mariadb://bbdd.juangabrielsv.dev:3306/u665594306_bdapp
spring.datasource.username=u665594306_admin
spring.datasource.password=cra6Trek+
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Configuración de JPA e Hibernate.
spring.jpa.hibernate.ddl-auto=validate
# Muestra las consultas SQL que se realizan en el log de la aplicación.
spring.jpa.show-sql=true
# Cierra la sesión de JPA al terminar la capa de servicio o repositorio, evita consultas al recargar páginas.
spring.jpa.open-in-view=false

# Nivel del log.
logging.level.root=INFO